import { useState } from 'react';

interface SetUsernameProps {
  currentUsername: string;
  onSetUsername: (username: string) => Promise<void>;
}

export default function SetUsername({ currentUsername, onSetUsername }: SetUsernameProps) {
  const [username, setUsername] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const isAutoGenerated = /^[a-z0-9]+_[a-f0-9]{4}$/.test(currentUsername);

  const validateUsername = (value: string): string | null => {
    if (value.length < 3) return 'Username must be at least 3 characters';
    if (value.length > 20) return 'Username must be at most 20 characters';
    if (!/^[a-z0-9_]+$/.test(value)) return 'Only lowercase letters, numbers, and underscores';
    return null;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const validationError = validateUsername(username);
    if (validationError) {
      setError(validationError);
      return;
    }

    setError('');
    setLoading(true);
    try {
      await onSetUsername(username);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to set username';
      if (msg.includes('duplicate') || msg.includes('unique')) {
        setError('Username already taken');
      } else {
        setError(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  if (!isAutoGenerated) return null;

  return (
    <div className="flex flex-col items-center justify-center h-full px-8">
      <p className="text-5xl mb-2">🎮</p>
      <h1 className="text-xl font-bold font-mono neon-text-green mb-1">
        Pick a Username
      </h1>
      <p className="text-doom-muted text-xs mb-6 text-center">
        This is how other doomscrollers will find you.
      </p>

      <form onSubmit={handleSubmit} className="w-full space-y-4">
        <div>
          <div className="flex items-center bg-doom-surface border border-doom-border rounded-lg px-4 py-3">
            <span className="text-doom-muted text-sm mr-1">@</span>
            <input
              type="text"
              placeholder="your_username"
              value={username}
              onChange={(e) => {
                setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ''));
                setError('');
              }}
              maxLength={20}
              required
              className="flex-1 bg-transparent text-white placeholder-doom-muted text-sm
                         focus:outline-none"
            />
          </div>
          <p className="text-doom-muted text-[10px] mt-1 px-1">
            3-20 chars, lowercase, numbers, underscores
          </p>
        </div>

        {error && (
          <p className="text-neon-pink text-xs text-center">{error}</p>
        )}

        <button
          type="submit"
          disabled={loading || username.length < 3}
          className="w-full btn-primary py-3 font-bold text-sm disabled:opacity-50"
        >
          {loading ? 'Setting...' : 'Claim Username'}
        </button>
      </form>
    </div>
  );
}
