import { useEffect, useState } from 'react';
import { useAuth } from './hooks/useAuth';
import Login from './pages/Login';
import Signup from './pages/Signup';
import SetUsername from './pages/SetUsername';
import Dashboard from './pages/Dashboard';
import Profile from './pages/Profile';
import Friends from './pages/Friends';
import Leaderboard from './pages/Leaderboard';
import Settings from './pages/Settings';
import BottomNav from './components/BottomNav';

function App() {
  const {
    user,
    profile,
    loading,
    profileError,
    signIn,
    signUp,
    signOut,
    updateUsername,
    refreshProfile,
  } = useAuth();
  const [authView, setAuthView] = useState<'login' | 'signup'>('login');
  const [activePage, setActivePage] = useState('home');
  const [viewingProfileId, setViewingProfileId] = useState<string | null>(null);

  useEffect(() => {
    // Prevent stale page state (for example, staying on Settings) across logout/login user changes.
    setActivePage('home');
    setViewingProfileId(null);
    if (!user) setAuthView('login');
  }, [user?.id]);

  if (loading) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg flex items-center justify-center">
        <div className="text-center">
          <p className="text-4xl mb-3 animate-pulse-neon">💀</p>
          <p className="text-doom-muted font-mono text-xs">Loading...</p>
        </div>
      </div>
    );
  }

  // Not authenticated
  if (!user) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        {authView === 'login' ? (
          <Login
            onSignIn={async (email, password) => {
              await signIn(email, password);
            }}
            onSwitchToSignUp={() => setAuthView('signup')}
          />
        ) : (
          <Signup
            onSignUp={async (email, password, displayName) => {
              await signUp(email, password, displayName);
            }}
            onSwitchToLogin={() => setAuthView('login')}
          />
        )}
      </div>
    );
  }

  // Authenticated but profile still syncing/loading.
  if (!profile) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg flex items-center justify-center px-8">
        <div className="text-center space-y-3">
          <p className="text-doom-muted font-mono text-xs">
            {profileError ?? 'Syncing profile...'}
          </p>
          {profileError && (
            <div className="flex items-center justify-center gap-2">
              <button
                onClick={() => {
                  void refreshProfile();
                }}
                className="px-3 py-1.5 rounded-md border border-doom-border text-xs font-mono text-doom-muted hover:text-white hover:border-neon-green/40 transition-colors"
              >
                Retry
              </button>
              <button
                onClick={() => {
                  void signOut();
                }}
                className="px-3 py-1.5 rounded-md border border-doom-border text-xs font-mono text-doom-muted hover:text-neon-pink transition-colors"
              >
                Sign out
              </button>
            </div>
          )}
        </div>
      </div>
    );
  }

  const currentUser = user;
  const currentProfile = profile;

  // Authenticated but needs to set username
  const isAutoGenerated = /^[a-z0-9]+_[a-f0-9]{4}$/.test(currentProfile.username);
  if (isAutoGenerated) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        <SetUsername
          currentUsername={currentProfile.username}
          onSetUsername={updateUsername}
        />
      </div>
    );
  }

  // Render the active page
  function renderPage() {
    switch (activePage) {
      case 'home':
        return <Dashboard />;
      case 'board':
        return (
          <Leaderboard
            userId={currentUser.id}
            onViewProfile={(id) => {
              setViewingProfileId(id);
              setActivePage('profile');
            }}
          />
        );
      case 'pals':
        return (
          <Friends
            userId={currentUser.id}
            onViewProfile={(id) => {
              setViewingProfileId(id);
              setActivePage('profile');
            }}
          />
        );
      case 'battle':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">Battles coming in v3...</div>;
      case 'chat':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">AI Chat coming in v2...</div>;
      case 'profile':
        return (
          <Profile
            userId={viewingProfileId ?? currentUser.id}
            isOwnProfile={!viewingProfileId || viewingProfileId === currentUser.id}
            onBack={viewingProfileId ? () => setActivePage('home') : undefined}
            cachedProfile={(!viewingProfileId || viewingProfileId === currentUser.id) ? currentProfile : undefined}
          />
        );
      case 'settings':
        return (
          <Settings
            profile={currentProfile}
            onSignOut={signOut}
            onProfileUpdated={() => {
              // Profile will auto-refresh via useAuth listener
            }}
          />
        );
      default:
        return <Dashboard />;
    }
  }

  // Fully authenticated
  return (
    <div className="w-[400px] h-[600px] bg-doom-bg text-white flex flex-col">
      <header className="flex items-center justify-between px-4 py-3 border-b border-doom-border">
        <h1 className="text-lg font-bold font-mono neon-text-green">
          DoomScroller
        </h1>
        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              setViewingProfileId(null);
              setActivePage('profile');
            }}
            className="text-doom-muted text-xs font-mono hover:text-neon-cyan transition-colors"
          >
            @{currentProfile.username}
          </button>
          <button
            onClick={() => setActivePage('settings')}
            className="text-doom-muted hover:text-white text-sm transition-colors"
            title="Settings"
          >
            ⚙
          </button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-4">
        {renderPage()}
      </main>

      <BottomNav active={activePage} onNavigate={setActivePage} />
    </div>
  );
}

export default App;
