import { useState } from 'react';
import { useAuth } from './hooks/useAuth';
import Login from './pages/Login';
import Signup from './pages/Signup';
import SetUsername from './pages/SetUsername';
import Dashboard from './pages/Dashboard';
import Profile from './pages/Profile';
import BottomNav from './components/BottomNav';

function App() {
  const { user, profile, loading, signIn, signUp, signOut, updateUsername } = useAuth();
  const [authView, setAuthView] = useState<'login' | 'signup'>('login');
  const [activePage, setActivePage] = useState('home');
  const [viewingProfileId, setViewingProfileId] = useState<string | null>(null);

  if (loading) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg flex items-center justify-center">
        <div className="text-center">
          <p className="text-4xl mb-3 animate-pulse-neon">💀</p>
          <p className="text-doom-muted font-mono text-xs">Loading...</p>
        </div>
      </div>
    );
  }

  // Not authenticated
  if (!user) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        {authView === 'login' ? (
          <Login
            onSignIn={async (email, password) => {
              await signIn(email, password);
            }}
            onSwitchToSignUp={() => setAuthView('signup')}
          />
        ) : (
          <Signup
            onSignUp={async (email, password, displayName) => {
              await signUp(email, password, displayName);
            }}
            onSwitchToLogin={() => setAuthView('login')}
          />
        )}
      </div>
    );
  }

  // Authenticated but needs to set username
  const isAutoGenerated = profile?.username && /^[a-z0-9]+_[a-f0-9]{4}$/.test(profile.username);
  if (isAutoGenerated) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        <SetUsername
          currentUsername={profile.username}
          onSetUsername={updateUsername}
        />
      </div>
    );
  }

  // Render the active page
  function renderPage() {
    switch (activePage) {
      case 'home':
        return <Dashboard />;
      case 'board':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">Leaderboard coming soon...</div>;
      case 'pals':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">Friends coming soon...</div>;
      case 'battle':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">Battles coming in v3...</div>;
      case 'chat':
        return <div className="text-center text-doom-muted py-8 font-mono text-sm">AI Chat coming in v2...</div>;
      case 'profile':
        return (
          <Profile
            userId={viewingProfileId ?? user!.id}
            isOwnProfile={!viewingProfileId || viewingProfileId === user!.id}
            onBack={viewingProfileId ? () => setActivePage('home') : undefined}
          />
        );
      default:
        return <Dashboard />;
    }
  }

  // Fully authenticated
  return (
    <div className="w-[400px] h-[600px] bg-doom-bg text-white flex flex-col">
      <header className="flex items-center justify-between px-4 py-3 border-b border-doom-border">
        <h1 className="text-lg font-bold font-mono neon-text-green">
          DoomScroller
        </h1>
        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              setViewingProfileId(null);
              setActivePage('profile');
            }}
            className="text-doom-muted text-xs font-mono hover:text-neon-cyan transition-colors"
          >
            @{profile?.username}
          </button>
          <button
            onClick={signOut}
            className="text-doom-muted hover:text-neon-pink text-xs transition-colors"
          >
            ✕
          </button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto p-4">
        {renderPage()}
      </main>

      <BottomNav active={activePage} onNavigate={setActivePage} />
    </div>
  );
}

export default App;
