import { useState } from 'react';
import { HashRouter, Routes, Route, Navigate } from 'react-router-dom';
import { useAuth } from './hooks/useAuth';
import Login from './pages/Login';
import Signup from './pages/Signup';
import SetUsername from './pages/SetUsername';

function AuthenticatedApp() {
  return (
    <div className="flex flex-col items-center justify-center h-full gap-4">
      <p className="text-6xl">💀</p>
      <p className="text-doom-muted font-mono text-sm">You're in. Building dashboard...</p>
    </div>
  );
}

function App() {
  const { user, profile, loading, signIn, signUp, signOut, updateUsername } = useAuth();
  const [authView, setAuthView] = useState<'login' | 'signup'>('login');

  if (loading) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg flex items-center justify-center">
        <div className="text-center">
          <p className="text-4xl mb-3 animate-pulse-neon">💀</p>
          <p className="text-doom-muted font-mono text-xs">Loading...</p>
        </div>
      </div>
    );
  }

  // Not authenticated
  if (!user) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        {authView === 'login' ? (
          <Login
            onSignIn={async (email, password) => {
              await signIn(email, password);
            }}
            onSwitchToSignUp={() => setAuthView('signup')}
          />
        ) : (
          <Signup
            onSignUp={async (email, password, displayName) => {
              await signUp(email, password, displayName);
            }}
            onSwitchToLogin={() => setAuthView('login')}
          />
        )}
      </div>
    );
  }

  // Authenticated but needs to set username
  const isAutoGenerated = profile?.username && /^[a-z0-9]+_[a-f0-9]{4}$/.test(profile.username);
  if (isAutoGenerated) {
    return (
      <div className="w-[400px] h-[600px] bg-doom-bg text-white">
        <SetUsername
          currentUsername={profile.username}
          onSetUsername={updateUsername}
        />
      </div>
    );
  }

  // Fully authenticated
  return (
    <HashRouter>
      <div className="w-[400px] h-[600px] bg-doom-bg text-white flex flex-col">
        <header className="flex items-center justify-between px-4 py-3 border-b border-doom-border">
          <h1 className="text-lg font-bold font-mono neon-text-green">
            DoomScroller
          </h1>
          <div className="flex items-center gap-2">
            <span className="text-doom-muted text-xs font-mono">
              @{profile?.username}
            </span>
            <button
              onClick={signOut}
              className="text-doom-muted hover:text-neon-pink text-xs transition-colors"
            >
              ✕
            </button>
          </div>
        </header>

        <main className="flex-1 overflow-y-auto p-4">
          <Routes>
            <Route path="/" element={<AuthenticatedApp />} />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </main>
      </div>
    </HashRouter>
  );
}

export default App;
